### ISSUE TITLE
🦭 balls

### ISSUE THREAD

**Issue by loud1337** [ballsballsballsballsballsballsballsball/Balls#4]
balls 🦭

_Originally posted by @ballsballsballsballsballsballsballsball in https://github.com/ballsballsballsballsballsballsballsball/Balls/issues/2#issuecomment-787458344_

**Comment by ballsballsballsballsballsballsballsball** [comment]
I refuse to fix this issue.

**Comment by loud1337** [comment]
NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO


ples fix
