### ISSUE TITLE
OMG LOOK AT THIS!!! DREAM SPEEDRUNS PERFECTLY WITH NO MISTAKES!! MUST WATCH!!

### ISSUE THREAD

**Issue by ch1ck3n-byte** [ballsballsballsballsballsballsballsball/Balls#57]
ok now i have your attention

i hereby present to you:

https://pypi.org/project/balls/0.0.1/

the "balls python module"!

created by me.

documentation here:
https://github.com/ch1ck3n-byte/balls-docs/blob/main/README.md

**Comment by troIIing** [comment]
:dababy:

**Comment by ch1ck3n-byte** [comment]
@trolling

are you a bot

**Comment by troIIing** [comment]
hi also join discord https://discord.gg/X7nkbnXP thx

**Comment by troIIing** [comment]
no

**Comment by troIIing** [comment]
I am not a bot, and this action was done manually.

**Comment by ch1ck3n-byte** [comment]
> I am not a bot, and this action was done manually.

lol
