### ISSUE TITLE
[FEATURE] Bigger balls

### ISSUE THREAD

**Issue by chocopie69** [ballsballsballsballsballsballsballsball/Balls#91]
draw bigger balls
cum sex moment

**Comment by NathanKassab** [comment]
yes we need bigger balls

**Comment by jesse103** [comment]
I agree

**Comment by Unzor** [comment]
yes

**Comment by MultiFrosty** [comment]
And what about cbt

**Comment by cheeziess** [comment]
cock and ball torture
from
wikipedia
available
at
en.
wikipedia
.org
the
free encyclopedia

**Comment by chocopie69** [comment]
cbt is cock and balls torture.
do not cbt. only bt.

**Comment by MultiFrosty** [comment]
There is a possibility to consider the option of surgically enlarging balls

**Comment by ballsballsballsballsballsballsballsball** [comment]
Hi

**Comment by Unzor** [comment]
Hi

**Comment by aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa4** [comment]
i want big penis

**Comment by GrpeApple** [comment]
agree
